# Generated by Django 5.1.6 on 2025-08-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TreatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_method', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['treatment_method'],
                'unique_together': {('treatment_method', 'user')},
            },
        ),
    ]
