# Generated by Django 5.1.6 on 2025-08-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_growthform_user_treatmentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('species_name', models.CharField(max_length=200)),
                ('genus', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('afrikaans_name', models.CharField(max_length=100)),
                ('growth_form', models.CharField(max_length=100)),
                ('WC', models.BooleanField(default=False)),
                ('NC', models.BooleanField(default=False)),
                ('KZN', models.BooleanField(default=False)),
                ('GTG', models.BooleanField(default=False)),
                ('MPL', models.BooleanField(default=False)),
                ('FS', models.BooleanField(default=False)),
                ('EC', models.BooleanField(default=False)),
                ('LMP', models.BooleanField(default=False)),
                ('NW', models.BooleanField(default=False)),
                ('initial_reduction', models.FloatField(blank=True, null=True)),
                ('follow_up_reduction', models.FloatField(blank=True, null=True)),
                ('treatment_frequency', models.IntegerField(blank=True, null=True)),
                ('densification', models.IntegerField(blank=True, null=True)),
                ('flow_optimal', models.FloatField(blank=True, null=True)),
                ('flow_sub_optimal', models.FloatField(blank=True, null=True)),
                ('flow_young', models.FloatField(blank=True, null=True)),
                ('flow_seedling', models.FloatField(blank=True, null=True)),
                ('flow_coppice', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
