# Generated by Django 5.1.6 on 2025-08-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='ref_id',
        ),
    ]
