# Generated by Django 5.1.6 on 2025-08-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_species_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='growth_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='support.growthform'),
        ),
    ]
