# Generated by Django 5.1.6 on 2025-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_species_growth_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='afrikaans_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
