# Generated by Django 5.1.6 on 2025-08-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_species_afrikaans_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbicide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbicide', models.CharField(max_length=100)),
                ('cost_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litres_per_hectare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_ingredient', models.CharField(max_length=255)),
                ('registration_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
