# Generated by Django 5.1.6 on 2025-08-07 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_herbicide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearingNormSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClearingNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField()),
                ('process', models.CharField(choices=[('Initial', 'Initial'), ('Follow-up', 'Follow-up')], max_length=20)),
                ('size_class', models.CharField(choices=[('All', 'All'), ('Seedling', 'Seedling'), ('Young', 'Young'), ('Adult', 'Adult')], max_length=20)),
                ('terrain', models.CharField(choices=[('Landscape', 'Landscape'), ('Riparian', 'Riparian')], max_length=20)),
                ('ppd', models.FloatField()),
                ('growth_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.growthform')),
                ('treatment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.treatmentmethod')),
                ('clearing_norm_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='support.clearingnormset')),
            ],
        ),
    ]
