# Generated by Django 5.1.6 on 2025-08-07 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_clearingnormset_clearingnorm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearingnorm',
            name='process',
            field=models.CharField(choices=[('Initial', 'initial'), ('Follow-up', 'follow-up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clearingnorm',
            name='size_class',
            field=models.CharField(choices=[('All', 'all'), ('Seedling', 'seedling'), ('Young', 'young'), ('Adult', 'adult')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clearingnorm',
            name='terrain',
            field=models.CharField(choices=[('Landscape', 'landscape'), ('Riparian', 'riparian')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='clearingnormset',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_per_user'),
        ),
    ]
