# Generated by Django 5.1.6 on 2025-08-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_clearingnorm_process_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Costing Model Name')),
                ('initial_team_size', models.PositiveIntegerField()),
                ('initial_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('followup_team_size', models.PositiveIntegerField()),
                ('followup_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_level', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cost_item', models.CharField(max_length=200)),
                ('daily_item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cost_items', to='support.costingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
