# Generated by Django 5.1.6 on 2025-08-11 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_costingmodel_dailycostitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='costingmodel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_model_name_per_user'),
        ),
    ]
