# Generated by Django 5.1.6 on 2025-08-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_costingmodel_unique_model_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text')], max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Null for default categories', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NumericPriorityBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_low', models.FloatField()),
                ('range_high', models.FloatField()),
                ('priority', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_bands', to='support.category')),
            ],
            options={
                'ordering': ['range_low'],
                'unique_together': {('category', 'range_low', 'range_high')},
            },
        ),
        migrations.CreateModel(
            name='TextPriorityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(max_length=200)),
                ('priority', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_values', to='support.category')),
            ],
            options={
                'ordering': ['text_value'],
                'unique_together': {('category', 'text_value')},
            },
        ),
    ]
