# Generated by Django 5.1.6 on 2025-08-12 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_category_numericpriorityband_textpriorityvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='A value between 0 and 1 inclusive', max_digits=3),
        ),
    ]
