# Generated by Django 5.2.5 on 2025-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_category_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costingmodel',
            name='maintenance_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
