# Generated by Django 5.2.5 on 2025-09-23 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_alter_costingmodel_maintenance_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=0.0, help_text='A value between 0 and 1 inclusive', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='costingmodel',
            name='followup_cost_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='costingmodel',
            name='fuel_cost_per_hour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='costingmodel',
            name='initial_cost_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='costingmodel',
            name='vehicle_cost_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailycostitem',
            name='daily_item_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='herbicide',
            name='cost_per_litre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='herbicide',
            name='litres_per_hectare',
            field=models.FloatField(),
        ),
    ]
