# Generated by Django 5.1.6 on 2025-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planning_user'),
        ('support', '0013_category_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='category',
        ),
        migrations.AddField(
            model_name='planning',
            name='categories',
            field=models.ManyToManyField(related_name='plannings', to='support.category'),
        ),
    ]
