# Generated by Django 5.1.6 on 2025-08-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_remove_planning_category_planning_categories'),
        ('support', '0013_category_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='categories',
        ),
        migrations.CreateModel(
            name='PlanningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.category')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_categories', to='planning.planning')),
            ],
            options={
                'unique_together': {('planning', 'category')},
            },
        ),
    ]
