# Generated by Django 5.1.6 on 2025-08-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_planning_categories_planningcategory'),
        ('support', '0013_category_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCostingMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costing_value', models.CharField(max_length=100)),
                ('costing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.costingmodel')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_mappings', to='planning.planning')),
            ],
            options={
                'unique_together': {('planning', 'costing_value')},
            },
        ),
    ]
