# Generated by Django 5.1.6 on 2025-08-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_planningcostingmapping'),
        ('support', '0013_category_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='costing_model',
        ),
        migrations.AddField(
            model_name='planning',
            name='clearing_norm_model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='support.clearingnormset'),
            preserve_default=False,
        ),
    ]
