# Generated by Django 5.1.6 on 2025-08-25 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_remove_planning_costing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='standard_working_year_days',
            field=models.PositiveIntegerField(default=220, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='standard_working_day',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
