# Generated by Django 5.2.5 on 2025-09-23 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_planning_standard_working_year_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='budget_plan_1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='budget_plan_2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='budget_plan_3',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='budget_plan_4',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='escalation_plan_1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='escalation_plan_2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='escalation_plan_3',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='escalation_plan_4',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='planning',
            name='standard_working_day',
            field=models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(24.0)]),
        ),
    ]
