# Generated by Django 5.1.6 on 2025-08-12 00:57

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compartments_shp', models.FileField(upload_to=project.models.project_directory_path)),
                ('miu_shp', models.FileField(upload_to=project.models.project_directory_path)),
                ('nbal_shp', models.FileField(upload_to=project.models.project_directory_path)),
                ('gis_mapping_shp', models.FileField(upload_to=project.models.project_directory_path)),
                ('compartment_priorities_csv', models.FileField(upload_to=project.models.project_directory_path)),
                ('miu_linked_species_excel', models.FileField(upload_to=project.models.project_directory_path)),
                ('nbal_linked_species_excel', models.FileField(upload_to=project.models.project_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
