# Generated by Django 5.1.6 on 2025-08-13 09:50

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='compartments_shp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gis_mapping_shp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='miu_shp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nbal_shp',
        ),
        migrations.AlterField(
            model_name='project',
            name='compartment_priorities_csv',
            field=models.FileField(blank=True, null=True, upload_to=project.models.project_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='miu_linked_species_excel',
            field=models.FileField(blank=True, null=True, upload_to=project.models.project_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='nbal_linked_species_excel',
            field=models.FileField(blank=True, null=True, upload_to=project.models.project_directory_path),
        ),
        migrations.CreateModel(
            name='CompartmentShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.project_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartment_shapefiles', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'compartments',
            },
        ),
        migrations.CreateModel(
            name='GISMappingShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.project_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gis_mapping_shapefiles', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'gis_mapping',
            },
        ),
        migrations.CreateModel(
            name='MIUShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.project_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miu_shapefiles', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'miu',
            },
        ),
        migrations.CreateModel(
            name='NBALShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.project_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nbal_shapefiles', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'nbal',
            },
        ),
    ]
