# Generated by Django 5.1.6 on 2025-08-14 22:31

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_compartments_shp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gismappingshapefile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='miushapefile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='nbalshapefile',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='compartment_dbf',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='compartment_prj',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='compartment_shp',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='compartment_shx',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gis_mapping_dbf',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gis_mapping_prj',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gis_mapping_shp',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gis_mapping_shx',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='miu_dbf',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='miu_prj',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='miu_shp',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='miu_shx',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='nbal_dbf',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='nbal_prj',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='nbal_shp',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='nbal_shx',
            field=models.FileField(default='', upload_to=project.models.project_directory_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompartmentShapefile',
        ),
        migrations.DeleteModel(
            name='GISMappingShapefile',
        ),
        migrations.DeleteModel(
            name='MIUShapefile',
        ),
        migrations.DeleteModel(
            name='NBALShapefile',
        ),
    ]
