# Generated by Django 5.2.5 on 2025-09-18 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0009_planning_standard_working_year_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('optimal', 'Optimal'), ('budget_1', 'Budget 1'), ('budget_2', 'Budget 2'), ('budget_3', 'Budget 3'), ('budget_4', 'Budget 4')], max_length=20)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='planning.planning')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_results', to='visualization.budgetscenario')),
            ],
            options={
                'unique_together': {('budget', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SimulationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbal_id', models.CharField(max_length=50)),
                ('miu_id', models.CharField(max_length=50)),
                ('compt_id', models.CharField(max_length=50)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('person_days', models.FloatField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField()),
                ('flow', models.FloatField()),
                ('cleared_now', models.BooleanField(default=False)),
                ('cleared_fully', models.BooleanField(default=False)),
                ('yearly_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='visualization.yearlyresult')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationBudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('plan_1', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_2', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_3', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_4', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_years', to='planning.planning')),
            ],
            options={
                'unique_together': {('planning', 'year')},
            },
        ),
    ]
