# Generated by Django 5.2.5 on 2025-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_alter_simulationbudgetyear_plan_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrow',
            name='compt_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simulationrow',
            name='miu_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simulationrow',
            name='nbal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
